version: '3'
services:
  ch:
    image: "yandex/clickhouse-server:1.1.54380"
    volumes:
      - "./clickhouse/log:/var/log/clickhouse-server"
      - "./clickhouse/config/config.xml:/etc/clickhouse-server/config.xml"
      - "./clickhouse/data:/var/lib/clickhouse"
    environment:
      - "TZ=Asia/Hong_Kong"
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: "always"
